server:
  port: 5000
security:
  basic:
    realm: animes
  user:
    name: user
    password: 1
spring:
  jackson:
    date-format: yyyy-MM-dd
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aneemays
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true